インデントの置き換え
KazuyaOrimoto/CrystalBreak pull request #1
Opened 2019-05-18 02:58 UTC by KazuyaOrimoto

リファクタリングが終わっているファイルの
タブで空白を開けていたところをスペースに書き換えました。

2019-05-18 03:33 UTC, vm-t-yui approved these changes

2019-05-18 03:33 UTC, vm-t-yui requested changes
何見たらいいか書いてください

2019-05-18 05:02 UTC, KazuyaOrimoto commented
@vm-t-yui 
・SceneBaseクラスのリファクタリングは正しく出来ているか
・main、Gameクラス、SceneBaseクラスのインデントにおかしいところはないか
以上2点のチェックをお願いします。

2019-05-18 10:34 UTC, vm-t-yui requested changes

2019-05-18 10:34 UTC, vm-t-yui commented on Common.h
> +typedef std::vector<EnemyBase*> EnemyVector;
[nits]
vectorだと意味が被るから個人的にはコンテナとかにしたい・・・

2019-05-18 10:34 UTC, vm-t-yui commented on Common.h
> +struct IndexPair
commonに書くんじゃなくてここまできたらIndexPair.hをつくろう

2019-05-18 10:34 UTC, vm-t-yui commented on Game.cpp
> +bool Game::IsContinueGame()
関数コメントがないぞ

2019-05-18 10:34 UTC, vm-t-yui commented on SceneBase.cpp
> +SceneBase::SceneBase()
空の関数の中にはコメントをつける

2019-05-18 10:34 UTC, vm-t-yui commented on TitleScene.h
> +	InputManager    *inputManager;                  //入力管理クラスのポインタ
ポインタ用のアスタリスクは型のほうにつける

2019-05-18 10:34 UTC, vm-t-yui commented on TitleScene.h
> +	const int       OPACITY_MAX = 80;                     //タイトルでアニメーションさせる画像の不透明度の上限値（0~255）
constで定数ならstatic型にしよう

2019-05-19 09:03 UTC, KazuyaOrimoto commented
指摘されている部分はわかる範囲で修正しました。
空の関数にどんなコメントをつければいいのかがわからなかったので、
実体をヘッダーに移動させました。

2019-05-20 06:17 UTC, vm-t-yui approved these changes
置き換えのみのようなのでApprove

2019-05-20 06:17 UTC, merged